server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.22:3306/woorionebank?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate.default_batch_fetch_size: 1000
        hibernate.format_sql: true

servlet:
  multipart:
    max-file-size: 30MB
    max-request-size: 500MB

# swagger
springdoc:
  api-docs:
    path: /api-docs # API 문서 생성 경로
    groups:
      enabled: true
  swagger-ui:
    path: /index.html   # Swagger-ui 경로
    enabled: true       # Swagger UI가 활성화
    groups-order: asc   # API 그룹을 오름차순 정렬
    tags-sorter: alpha  # 태그를 알파벳 순 정렬
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: false  # 캐싱을 비활성화할 지 여부를 결정
  override-with-generic-response: false
  model-and-view-allowed: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json # 데이터를 생성하는 기본 유형을 지정